name: Maven Package

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: dt-csg-runtime
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0'
        distribution: 'temurin'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the Container image
      run: docker build -t pcsparsing .        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image to Docker hub
      run: |
          docker tag pcsparsing:latest mahendra83/pcsparsing:latest
    - name: Run Docker image
      run: docker run --name pcsparsingear -d -p 9080:9080 mahendra83/pcsparsing:latest
          docker push mahendra83/pcsparsing:latest
