name: Maven Package

on:
  push:
    branches:
    - main
    - release/*

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: 686255956504.dkr.ecr.us-west-2.amazonaws.com/dtna-ns/registry

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0'
        distribution: 'temurin'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: Build with Maven
#      run: mvn -B package --file pom.xml    
#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
#      uses: aws-actions/configure-aws-credentials@v2
#      with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}
#      run: dt-aws-aad-sso login -p dtna-aws-test -r UnITe-Developer  
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
